const mongo = require('mongoose')

module.exports = mongo.model(
    'Money',
    new mongo.Schema({
        id: String,
        userId: String,
        userBit: String,
        userVip: String,
        userName: String,
        userJp: String,
        userDoski: String,
        userBp: String,
        userKirp: String,
        userHouse: String,
        userCem: String,
        userCar: String,
        userBannedacc: String,
        userStavka: String,
        userBankRob: String,
        userRobProg: String,
        userHealth: String,
        userBanReason: String,
        userCurse: String,
        userJob: String,
        jobprogress: Number,
        userAdmin: String,
        userFerms: String,
        userEnergy: String,
        userReg: String,
        userObezb: String,
        userTabl: String,
        userAnti: String,
        VIP: Number,
        obezb: Number,
        anti: Number,
        tabl: Number,
        coins: Number,
        bankcoins: Number,
        bitcoins: Number,
        bp: Number,
        house: Number,
        doski: Number,
        health: Number,
        kirp: Number,
        car: Number,
        cem: Number,
        stavka: Number,
        bankrob: Number,
        robprog: Number,
        reason: String,
        energy: Number,
        banacc: Number,
        curse: Number,
        job: String,
        name: String,
        register: Number,
        ferms: Number,
        ADMIN: Number,
    })
)


/*module.exports = mongo.model(
    'Banks',
    new mongo.Schema({
        userId: String,
        bankcoins: Number,
    })
)*/